name: deploy_prod
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          # 708486028818 == security-prod
          token_format: 'access_token'
          workload_identity_provider: 'projects/<your GCP project #>/locations/global/workloadIdentityPools/<your pool name>/providers/github'
          service_account: '<service_account_email>'
      
      - name: Login to GCR
        uses: 'docker/login-action@v2'
        with:
          registry: 'gcr.io' # or REGION-docker.pkg.dev for GAR
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
      
      - name: 'publish new image'
        run: make publish
      
      - name: 'update cloud run'
        run: gcloud run deploy <cr_service_name> --image=gcr.io/${{ steps.auth.outputs.project_id }}/<container_name>:latest --region=us-central1
